region                = "us-east-1"
project_name          = "project-name"
environment           = "stage"
domain                = "domain"
user_cognito_email    = "teste@teste.com"
user_cognito_password = "Teste123"
group_cognito_name    = "admin"
